CREATE INDEX clients_name_idx ON SYS.CLIENTS_OBJ (name);

CREATE INDEX tasks_status_idx ON SYS.TASKS_OBJ (status);

EXPLAIN PLAN FOR
SELECT *
FROM SYS.CLIENTS_OBJ
WHERE name LIKE 'Компания%';

SELECT *
FROM TABLE (DBMS_XPLAN.DISPLAY);

EXPLAIN PLAN FOR
SELECT *
FROM SYS.TASKS_OBJ
WHERE status = 'В работе';

SELECT *
FROM TABLE (DBMS_XPLAN.DISPLAY);
